remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
google_analytics: 10111740214
title: Charlie Jubera Portfolio
description: Overview of data science work